import { Octokit } from '@octokit/rest';
import { createAppAuth } from '@octokit/auth-app';

type GitHubMode = 'org' | 'user';

let cachedAppOctokit: Octokit | null = null;
let cachedUserOctokit: Octokit | null = null;

const resolveMode = (): GitHubMode => {
  const explicit = (process.env.GITHUB_MODE as GitHubMode | undefined)?.toLowerCase();
  if (explicit === 'org' || explicit === 'user') return explicit;
  // 自動判定: PAT があれば user、なければ org
  if (process.env.GITHUB_PERSONAL_ACCESS_TOKEN) return 'user';
  return 'org';
};

const getOrgOctokit = async (): Promise<{ client: Octokit; owner: string }> => {
  if (cachedAppOctokit) {
    return { client: cachedAppOctokit, owner: process.env.GITHUB_REPO_OWNER! };
  }

  const appId = process.env.GITHUB_APP_ID;
  const privateKey = process.env.GITHUB_APP_PRIVATE_KEY?.replace(/\\n/g, '\n');
  const owner = process.env.GITHUB_REPO_OWNER;

  if (!appId || !privateKey || !owner) {
    throw new Error('GitHub App environment variables are not set');
  }

  const appAuth = createAppAuth({ appId, privateKey });

  const installationAuth = await appAuth({ type: 'app' });
  const tempClient = new Octokit({ auth: installationAuth.token });
  const { data: installations } = await tempClient.apps.listInstallations();
  const installation = installations.find((i) => (i.account as any)?.login === owner);
  if (!installation) {
    throw new Error(`GitHub App not installed for owner: ${owner}`);
  }

  const { token } = await appAuth({ type: 'installation', installationId: installation.id });
  cachedAppOctokit = new Octokit({ auth: token });
  return { client: cachedAppOctokit, owner };
};

const getUserOctokit = async (): Promise<Octokit> => {
  if (cachedUserOctokit) return cachedUserOctokit;
  const pat = process.env.GITHUB_PERSONAL_ACCESS_TOKEN;
  if (!pat) throw new Error('GITHUB_PERSONAL_ACCESS_TOKEN is not set');
  cachedUserOctokit = new Octokit({ auth: pat });
  return cachedUserOctokit;
};

export const getOctokit = async (): Promise<Octokit> => {
  const mode = resolveMode();
  if (mode === 'user') {
    return getUserOctokit();
  }
  const { client } = await getOrgOctokit();
  return client;
};

export const createRepository = async (
  params: { name: string; description?: string; private?: boolean }
) => {
  const mode = resolveMode();
  const isPrivate = params.private ?? true;

  if (mode === 'user') {
    const client = await getUserOctokit();
    try {
      const res = await client.repos.createForAuthenticatedUser({
        name: params.name,
        description: params.description || 'Repository generated by AI Product Planner',
        private: isPrivate,
        auto_init: true,
      });
      return res.data;
    } catch (e: any) {
      // Improve error guidance for PAT scope issues
      const msg = e?.message || '';
      if (e?.status === 403 || /Resource not accessible by personal access token/i.test(msg)) {
        throw new Error(
          'GitHub PAT does not allow repository creation. Use a Classic PAT with repo scope, approve SSO if required, or use the "既存のリポジトリに適用" option.'
        );
      }
      throw e;
    }
  } else {
    const { client, owner } = await getOrgOctokit();
    const res = await client.repos.createInOrg({
      org: owner,
      name: params.name,
      description: params.description || 'Repository generated by AI Product Planner',
      private: isPrivate,
      auto_init: true,
    });
    return res.data;
  }
};

export const getRepoOwner = async (): Promise<string> => {
  const mode = resolveMode();
  if (mode === 'org') {
    const owner = process.env.GITHUB_REPO_OWNER;
    if (!owner) throw new Error('GITHUB_REPO_OWNER is not set');
    return owner;
  } else {
    const client = await getUserOctokit();
    const { data } = await client.users.getAuthenticated();
    return data.login;
  }
};

export const createOrUpdateFile = async (
  params: { repo: string; path: string; content: string; message?: string }
) => {
  const client = await getOctokit();
  const owner = await getRepoOwner();
  const contentBase64 = Buffer.from(params.content, 'utf-8').toString('base64');
  const message = params.message || `chore: add ${params.path}`;

  // Try to get existing file to include sha
  let sha: string | undefined;
  try {
    const existing = await client.repos.getContent({ owner, repo: params.repo, path: params.path });
    if (!Array.isArray(existing.data) && 'sha' in existing.data) {
      sha = (existing.data as any).sha;
    }
  } catch (_) {
    // not found -> create new
  }

  const res = await client.repos.createOrUpdateFileContents({
    owner,
    repo: params.repo,
    path: params.path,
    message,
    content: contentBase64,
    sha,
    branch: 'main',
  });
  return res.data;
};

export const getAuthInfo = async () => {
  const mode = resolveMode();
  if (mode === 'user') {
    const client = await getUserOctokit();
    const resp = await client.request('GET /user');
    // Scopes are in the response headers for classic PATs
    const scopes = (resp.headers as any)['x-oauth-scopes'] || null;
    return { mode, login: (resp.data as any).login, scopes };
  } else {
    const { client } = await getOrgOctokit();
    const resp = await client.request('GET /app');
    return { mode, appSlug: (resp.data as any).slug };
  }
};
