'use client';

import React, { useCallback, useMemo, useState } from 'react';

type Phase = 'intro' | 'requirements' | 'todos' | 'readme' | 'scaffold' | 'repo' | 'issues';

const suggestIntroPrompt = `あなたはプロダクトオーナーです。次の観点でアイデアを要約してください。
- 誰の、どんな課題を、どう解決するか（ユーザーペルソナ/ユースケース）
- コアとなる価値提案（USP）
- 最小実用プロダクト(MVP)の機能範囲
- 目標KPI（1～3個）`;

// 例の挿入時に入れる内容（placeholder は変更しない）
const exampleIntroInsert = [
  '簡単なtodoをプロンプトで操作できるアプリ',
  '・todolistを作成、アーカイブできる',
  '・todolistの中にtodoを追加、更新、削除ができる',
  '・todolist, todoそれぞれをプロンプトをうって自由に操作ができる',
].join('\n');

async function askLLM(content: string): Promise<string> {
  const res = await fetch('/api/chat', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ messages: [{ role: 'user', content }] }),
  });
  if (!res.ok) {
    const t = await res.text().catch(() => '');
    throw new Error(`LLM API error: ${res.status} ${t}`);
  }
  // APIはtext/plain返却（非ストリーミング）
  return res.text();
}

function buildRequirementsPrompt(productName: string, context: string) {
  return `プロダクト名: ${productName}\n\n文脈:\n${context}\n\n上記を踏まえて、要件定義（箇条書き）を日本語で出力してください。含める項目:\n- 対象ユーザー\n- ユースケース\n- 非機能要件（性能/信頼性/セキュリティ/運用）\n- MVPスコープ（Must/Should/Nice to have）\n出力はMarkdownで。`;
}

function buildTodosPrompt(requirementsMd: string) {
  return `以下の要件をもとにMVPの実装タスクを分解してください。\n\n${requirementsMd}\n\n出力条件:\n- Markdownのチェックリスト (- [ ]) 形式\n- 1タスクは2～6時間程度を目安に粒度調整\n- 並行可能なところはセクションで分ける`;
}

function buildReadmePrompt(productName: string, requirementsMd: string, todosMd: string) {
  return `次の要件とタスクをもとに、README.md の初版を日本語で生成してください。\n- タイトル: ${productName}\n- セクション: 概要 / 機能 / 要件 / セットアップ / 使い方 / 今後のTODO\n- コードブロックやコマンドはMarkdownで記述\n\n[要件]\n${requirementsMd}\n\n[TODO]\n${todosMd}`;
}

export default function Planner() {
  const [phase, setPhase] = useState<Phase>('intro');
  const [productName, setProductName] = useState('新規プロダクト');
  const [intro, setIntro] = useState('');
  const [requirements, setRequirements] = useState('');
  const [todos, setTodos] = useState('');
  const [readme, setReadme] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [repoName, setRepoName] = useState('new-product');
  const [repoDesc, setRepoDesc] = useState('Repository generated by AI Product Planner');
  const [useExistingRepo, setUseExistingRepo] = useState(false);
  const [authInfo, setAuthInfo] = useState<string | null>(null);
  const [repoResult, setRepoResult] = useState<string | null>(null);
  // Preview for auto-generated TODOs while still in requirements phase
  const [previewTodos, setPreviewTodos] = useState<string>('');
  const [previewTodosLoading, setPreviewTodosLoading] = useState(false);

  const canNextFromIntro = useMemo(() => intro.trim().length > 0, [intro]);
  const canNextFromReq = useMemo(() => requirements.trim().length > 0, [requirements]);
  const canNextFromTodos = useMemo(() => todos.trim().length > 0, [todos]);
  const canNextFromReadme = useMemo(() => readme.trim().length > 0, [readme]);

  const runRequirements = useCallback(async () => {
    setLoading(true); setError(null);
    try {
      let text = await askLLM(buildRequirementsPrompt(productName, intro));
      if (!text || !text.trim()) {
        // Fallback: 要件定義の枠（空返答対策）
        text = [
          `# 要件定義（叩き台）`,
          `- 対象ユーザー:`,
          `- ユースケース:`,
          `- 非機能要件: 性能/信頼性/セキュリティ/運用`,
          `- MVPスコープ: Must / Should / Nice to have`,
        ].join('\n');
      }
      setRequirements(text);
      setPhase('requirements');
      // reset previous preview when requirements changed
      setPreviewTodos('');
    } catch (e: any) {
      setError(e.message || '要件定義の生成に失敗しました');
    } finally { setLoading(false); }
  }, [productName, intro]);

  const runTodos = useCallback(async () => {
    setLoading(true); setError(null);
    try {
      const text = await askLLM(buildTodosPrompt(requirements));
      let next = text ?? '';
      if (!next.trim()) {
        // Fallback: derive a minimal checklist from requirements and conventions
        const fallback = [
          '## Frontend (Next.js + Storybook)',
          '- [ ] Setup Next.js app structure',
          '- [ ] Configure Storybook and add sample stories',
          '- [ ] Implement initial pages and components',
          '- [ ] Add ESLint/TS config and scripts',
          '',
          '## Backend (FastAPI + Strawberry GraphQL + Alembic)',
          '- [ ] Scaffold FastAPI app with Strawberry GraphQL at /graphql',
          '- [ ] Setup SQLAlchemy models and Alembic migration (init + first revision)',
          '- [ ] Add pytest and sample tests',
          '- [ ] Configure CORS and settings',
          '',
          '## Infrastructure',
          '- [ ] Prepare docker-compose (db/backend/migrate/frontend)',
          '- [ ] Add CI workflow for lint/test/build',
          '- [ ] Provide .env.example files',
        ].join('\n');
        next = fallback;
      }
      setTodos(next);
      setPhase('readme');
    } catch (e: any) {
      setError(e.message || 'TODOの生成に失敗しました');
    } finally { setLoading(false); }
  }, [requirements]);

  // TODOが空の場合、todosフェーズ到達時に自動生成して空欄を回避
  React.useEffect(() => {
    if (phase === 'todos' && !todos.trim() && requirements.trim() && !loading) {
      runTodos();
    }
  }, [phase, todos, requirements, loading, runTodos]);

  // Auto-generate TODO preview while staying on requirements phase
  const generateTodosPreview = useCallback(async () => {
    if (!requirements.trim()) return;
    setPreviewTodosLoading(true);
    try {
      const text = await askLLM(buildTodosPrompt(requirements));
      setPreviewTodos(text || '');
    } catch (e) {
      // keep silent, user can still click the main button
      setPreviewTodos('');
    } finally {
      setPreviewTodosLoading(false);
    }
  }, [requirements]);

  React.useEffect(() => {
    if (phase === 'requirements' && requirements.trim() && !previewTodos && !previewTodosLoading) {
      generateTodosPreview();
    }
  }, [phase, requirements, previewTodos, previewTodosLoading, generateTodosPreview]);

  const runReadme = useCallback(async () => {
    setLoading(true); setError(null);
    try {
      const text = await askLLM(buildReadmePrompt(productName, requirements, todos));
      setReadme(text);
      // 生成後は編集できるよう readme フェーズに留まる
      setPhase('readme');
    } catch (e: any) {
      setError(e.message || 'README生成に失敗しました');
    } finally { setLoading(false); }
  }, [productName, requirements, todos]);

  // README自動生成（遷移直後が空欄にならないように）
  React.useEffect(() => {
    if (phase === 'readme' && !readme.trim() && requirements.trim() && todos.trim() && !loading) {
      runReadme();
    }
  }, [phase, readme, requirements, todos, loading, runReadme]);

  const [previewFiles, setPreviewFiles] = useState<{ path: string; content: string }[] | null>(null);

  const loadPreview = useCallback(async () => {
    setLoading(true); setError(null);
    try {
      const res = await fetch('/api/scaffold/preview', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ productName, requirements, todos, readme }),
      });
      if (!res.ok) throw new Error(await res.text());
      const json = await res.json();
      setPreviewFiles(json.files);
    } catch (e: any) {
      setError(e.message || 'プレビューに失敗しました');
    } finally { setLoading(false); }
  }, [productName, requirements, todos, readme]);

  const applyScaffold = useCallback(async () => {
    if (!previewFiles) return;
    setLoading(true); setError(null);
    try {
      const res = await fetch('/api/scaffold/apply', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name: repoName, description: repoDesc, files: previewFiles, create: !useExistingRepo ? true : false }),
      });
      if (!res.ok) throw new Error(await res.text());
      setPhase('issues');
      setRepoResult(`作成しました: ${repoName}`);
    } catch (e: any) {
      setError(e.message || '適用に失敗しました');
    } finally { setLoading(false); }
  }, [previewFiles, repoName, repoDesc]);

  const checkGithubAuth = useCallback(async () => {
    setLoading(true); setError(null); setAuthInfo(null);
    try {
      const res = await fetch('/api/github/check-token');
      const text = await res.text();
      setAuthInfo(text);
    } catch (e: any) {
      setError(e.message || 'GitHub認証の確認に失敗しました');
    } finally { setLoading(false); }
  }, []);

  const createIssues = useCallback(async () => {
    setLoading(true); setError(null);
    try {
      const normalize = (md: string) => {
        const hasCheckbox = /\[\s?\]|\[x\]/i.test(md);
        if (hasCheckbox) return md;
        // 箇条書きをチェックリストに変換
        return md
          .split(/\r?\n/)
          .map((line) => {
            if (/^\s*[-*]\s+\S/.test(line)) {
              return line.replace(/^\s*([-*])\s+/, '- [ ] ');
            }
            if (/^\s*\d+\.\s+\S/.test(line)) {
              return line.replace(/^\s*\d+\.\s+/, '- [ ] ');
            }
            return line;
          })
          .join('\n');
      };
      const prepared = normalize(todos);
      const res = await fetch('/api/github/create-issues', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name: repoName, todos: prepared }),
      });
      if (!res.ok) throw new Error(await res.text());
      const json = await res.json();
      setRepoResult(`Issues 作成: ${json.count}件`);
    } catch (e: any) {
      setError(e.message || 'Issues作成に失敗しました');
    } finally { setLoading(false); }
  }, [repoName, todos]);

  const createRepo = useCallback(async () => {
    setLoading(true); setError(null); setRepoResult(null);
    try {
      const res = await fetch('/api/github/create-repo', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ name: repoName, description: repoDesc, readme }),
      });
      if (!res.ok) {
        const t = await res.text();
        throw new Error(`Repo create failed: ${res.status} ${t}`);
      }
      const json = await res.json();
      setRepoResult(`作成しました: ${json?.html_url || json?.full_name || repoName}`);
    } catch (e: any) {
      setError(e.message || 'リポジトリ作成に失敗しました');
    } finally { setLoading(false); }
  }, [repoName, repoDesc, readme]);

  return (
    <div className="flex-1 overflow-y-auto">
      <div className="max-w-4xl mx-auto p-4 space-y-6">
        <h2 className="text-2xl font-bold">AI Product Planner</h2>

        {error && (
          <div className="p-3 rounded bg-red-900/40 border border-red-700 text-red-200">{error}</div>
        )}

        <div className="flex gap-2 text-sm">
          {(['intro','requirements','todos','readme','repo'] as Phase[]).map((p) => (
            <span key={p} className={`px-2 py-1 rounded ${phase===p?'bg-blue-700':'bg-gray-700'}`}>{p}</span>
          ))}
        </div>

        {phase === 'intro' && (
          <section className="space-y-4">
            <div>
              <label className="block text-sm text-gray-300 mb-1">プロダクト名</label>
              <input className="w-full p-2 bg-gray-800 border border-gray-600 rounded" value={productName} onChange={(e)=>setProductName(e.target.value)} />
            </div>
            <div>
              <label className="block text-sm text-gray-300 mb-1">最初に入力してほしいプロンプト（例を修正して使えます）</label>
              <textarea className="w-full h-40 p-2 bg-gray-800 border border-gray-600 rounded" value={intro} onChange={(e)=>setIntro(e.target.value)} placeholder={suggestIntroPrompt} />
              <div className="mt-2">
                <button className="text-xs underline" onClick={()=>setIntro(exampleIntroInsert)}>例を挿入</button>
              </div>
            </div>
            <div className="flex gap-2">
              <button disabled={!canNextFromIntro||loading} onClick={runRequirements} className="bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded disabled:opacity-50">要件を生成</button>
            </div>
          </section>
        )}

        {phase === 'requirements' && (
          <section className="space-y-3">
            <h3 className="font-semibold">要件定義（編集可）</h3>
            <textarea className="w-full h-72 p-2 bg-gray-800 border border-gray-600 rounded" value={requirements} onChange={(e)=>setRequirements(e.target.value)} />
            <div className="flex gap-2">
              <button className="px-4 py-2 bg-gray-700 rounded" onClick={()=>setPhase('intro')}>戻る</button>
              <button disabled={!canNextFromReq||loading} onClick={runTodos} className="bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded disabled:opacity-50">TODOを生成</button>
            </div>
            <div className="mt-3 p-3 border border-gray-700 rounded bg-gray-800/40">
              <div className="flex items-center justify-between mb-2">
                <h4 className="font-semibold text-sm">自動生成されたTODOプレビュー</h4>
                <div className="flex gap-2">
                  <button className="px-2 py-1 bg-gray-700 rounded text-xs" onClick={generateTodosPreview} disabled={previewTodosLoading}>再生成</button>
                  <button className="px-2 py-1 bg-green-700 rounded text-xs" onClick={() => { if (previewTodos) { setTodos(previewTodos); setPhase('readme'); } }} disabled={!previewTodos || previewTodosLoading}>このTODOで次へ</button>
                </div>
              </div>
              {previewTodosLoading ? (
                <div className="text-xs opacity-80">生成中...</div>
              ) : (
                <textarea className="w-full h-48 p-2 bg-gray-900 border border-gray-700 rounded text-xs" value={previewTodos} onChange={(e)=>setPreviewTodos(e.target.value)} />
              )}
            </div>
          </section>
        )}

        {phase === 'todos' && (
          <section className="space-y-3">
            <h3 className="font-semibold">MVP TODO（編集可）</h3>
            <textarea className="w-full h-72 p-2 bg-gray-800 border border-gray-600 rounded" value={todos} onChange={(e)=>setTodos(e.target.value)} />
            <div className="flex gap-2">
              <button className="px-4 py-2 bg-gray-700 rounded" onClick={()=>setPhase('requirements')}>戻る</button>
              <button disabled={!canNextFromTodos||loading} onClick={runReadme} className="bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded disabled:opacity-50">READMEを生成</button>
            </div>
          </section>
        )}

        {phase === 'readme' && (
          <section className="space-y-3">
            <h3 className="font-semibold">README プレビュー（編集可）</h3>
            <textarea className="w-full h-96 p-2 bg-gray-800 border border-gray-600 rounded" value={readme} onChange={(e)=>setReadme(e.target.value)} />
            <div className="flex gap-2">
              <button className="px-4 py-2 bg-gray-700 rounded" onClick={()=>setPhase('todos')}>戻る</button>
              <button className="px-4 py-2 bg-gray-700 rounded" disabled={loading} onClick={runReadme}>READMEを生成</button>
              <button disabled={!canNextFromReadme||loading} onClick={()=>setPhase('scaffold')} className="bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded disabled:opacity-50">テンプレ確認へ進む</button>
            </div>
          </section>
        )}

        {phase === 'scaffold' && (
          <section className="space-y-3">
            <h3 className="font-semibold">テンプレート プレビュー</h3>
            <div className="flex gap-2 items-center">
              <button className="px-4 py-2 bg-gray-700 rounded" onClick={()=>setPhase('readme')}>戻る</button>
              <button className="px-4 py-2 bg-blue-600 rounded" disabled={loading} onClick={loadPreview}>プレビュー取得</button>
            </div>
            {previewFiles && (
              <div className="max-h-96 overflow-y-auto border border-gray-700 rounded">
                {previewFiles.map((f, i) => (
                  <details key={i} className="p-2 border-b border-gray-800">
                    <summary className="cursor-pointer text-sm text-blue-300">{f.path}</summary>
                    <pre className="whitespace-pre-wrap text-xs mt-2">{f.content}</pre>
                  </details>
                ))}
              </div>
            )}
            <div className="flex gap-2">
              <input className="w-1/2 p-2 bg-gray-800 border border-gray-600 rounded" value={repoName} onChange={(e)=>setRepoName(e.target.value)} placeholder="リポジトリ名" />
              <input className="w-1/2 p-2 bg-gray-800 border border-gray-600 rounded" value={repoDesc} onChange={(e)=>setRepoDesc(e.target.value)} placeholder="説明" />
            </div>
            <label className="flex items-center gap-2 text-sm">
              <input type="checkbox" checked={useExistingRepo} onChange={(e)=>setUseExistingRepo(e.target.checked)} />
              既存のリポジトリに適用（作成しない）
            </label>
            <div className="flex gap-2 items-center">
              <button className="px-3 py-1 bg-gray-700 rounded" onClick={checkGithubAuth} disabled={loading}>GitHubトークン確認</button>
              {authInfo && <span className="text-xs opacity-80">{authInfo}</span>}
            </div>
            <button className="px-4 py-2 bg-green-600 rounded disabled:opacity-50" disabled={loading || !previewFiles} onClick={applyScaffold}>テンプレ適用してリポ作成</button>
          </section>
        )}

        {phase === 'repo' && (
          <section className="space-y-3">
            <h3 className="font-semibold">リポジトリ作成</h3>
            <div>
              <label className="block text-sm text-gray-300 mb-1">リポジトリ名</label>
              <input className="w-full p-2 bg-gray-800 border border-gray-600 rounded" value={repoName} onChange={(e)=>setRepoName(e.target.value)} />
            </div>
            <div>
              <label className="block text-sm text-gray-300 mb-1">説明</label>
              <input className="w-full p-2 bg-gray-800 border border-gray-600 rounded" value={repoDesc} onChange={(e)=>setRepoDesc(e.target.value)} />
            </div>
            <div className="flex gap-2">
              <button className="px-4 py-2 bg-gray-700 rounded" onClick={()=>setPhase('readme')}>戻る</button>
              <button disabled={loading||!readme.trim()} onClick={createRepo} className="bg-green-600 hover:bg-green-700 px-4 py-2 rounded disabled:opacity-50">README付きで作成</button>
            </div>
            {repoResult && (
              <div className="p-3 rounded bg-emerald-900/40 border border-emerald-700 text-emerald-200 mt-2">{repoResult}</div>
            )}
          </section>
        )}

        {phase === 'issues' && (
          <section className="space-y-3">
            <h3 className="font-semibold">タスク(Issues)作成</h3>
            <p className="text-sm opacity-80">TODOの各行(- [ ])をIssueとして登録します。</p>
            <div className="flex gap-2">
              <button className="px-4 py-2 bg-gray-700 rounded" onClick={()=>setPhase('scaffold')}>戻る</button>
              <button className="px-4 py-2 bg-blue-600 rounded disabled:opacity-50" disabled={loading} onClick={createIssues}>Issues作成</button>
            </div>
            {repoResult && (
              <div className="p-3 rounded bg-emerald-900/40 border border-emerald-700 text-emerald-200 mt-2">{repoResult}</div>
            )}
          </section>
        )}

        {loading && <div className="text-sm opacity-80">処理中...</div>}
      </div>
    </div>
  );
}
