import { getOctokit } from '@/lib/github';
import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  try {
    const { name, description } = (await req.json()) as {
      name: string;
      description?: string;
    };
    const owner = process.env.GITHUB_REPO_OWNER!;

    const octokit = await getOctokit();

    const response = await octokit.repos.createInOrg({
      org: owner,
      name,
      description: description || 'Repository generated by AI Product Planner',
      private: true, // Default to private repositories
    });

    return NextResponse.json(response.data, { status: 201 });
  } catch (error: any) {
    console.error(error);
    return NextResponse.json(
      { message: error.message || 'Error creating repository' },
      { status: 500 }
    );
  }
}
